from __future__ import annotations

"""Generate environment-variation configs for Stage B (Phase-2).

The config loader does NOT merge partials, so each variant must be a full,
self-contained config. This script loads config/default.yaml, applies an
explicit, minimal set of overrides per variant, validates the result by
building a RunConfig, and writes config/env_<name>.yaml.

Because the config hash is taken over the *resolved* dict (sorted-key YAML
dump), comment loss from the round-trip is irrelevant to reproducibility:
the generated file resolves to exactly the documented overrides applied to
default.yaml.

Variants (the factor each one varies relative to the benign default):

  tight      - base cluster capacity lowered to the floor (6 CPU / 8 RAM) so
               the cluster is genuinely contended, but EVERY task still fits
               individually (max task demand is 6 CPU / 6 RAM). Scale_Up adds
               parallelism and lets more jobs finish before the 300-step
               truncation. Varies: CAPACITY PRESSURE (scaling raises throughput)
               WITHOUT triggering the do_action jam.

  loadfail   - node_failure mode per_node_bernoulli (each running task fails
               independently at prob 0.05), so concurrency raises the failure
               rate. Varies: DECISION-DEPENDENCE OF FAILURE (caution can
               reduce risk).

  tight_loadfail - both of the above.

Heavy-tailed value is a separate variant that needs a workload-generator
change and is produced once that lands (env_heavytail).

NOTE on the discarded `capacity` variant (a 12-CPU 'heavy' task > base 10):
it did NOT produce a clean scaling incentive. It instead triggered a
do_action pathology — Execute sorts ready tasks, tries only the TOP one, and
breaks if it does not fit, never falling through to the ~158 other fittable
ready tasks. A single high-value unfittable task starves the cluster
(298/300 steps were insufficient_resources, 0 completions). The MC probe's
large Scale_Up advantage there reflected unjamming a catastrophically jammed
baseline, not a realistic scaling-pays signal, and no fixed scaling policy
could exploit it. `env_tight` avoids the jam by keeping every task fittable.
"""

import copy
from pathlib import Path

import yaml

from src.config import REPO_ROOT, build_run_config

DEFAULT_PATH = REPO_ROOT / "config" / "default.yaml"


def _load_default_raw() -> dict:
    with DEFAULT_PATH.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def _tight(raw: dict) -> dict:
    raw = copy.deepcopy(raw)
    raw["meta"]["config_name"] = "env_tight"
    # Lower base capacity to the floor; scaling is the only way up. Every task
    # still fits (max demand 6 CPU / 6 RAM <= 6 / 8), so Execute never jams.
    raw["simulator"]["cluster"]["base_cpu_capacity"] = 6
    raw["simulator"]["cluster"]["base_ram_capacity"] = 8
    return raw


def _loadfail(raw: dict) -> dict:
    raw = copy.deepcopy(raw)
    raw["meta"]["config_name"] = "env_loadfail"
    raw["simulator"]["stochastic_processes"]["node_failure"]["mode"] = "per_node_bernoulli"
    # prob unchanged at 0.05 (now PER RUNNING TASK rather than per step).
    return raw


def _tight_loadfail(raw: dict) -> dict:
    raw = _tight(raw)
    raw["meta"]["config_name"] = "env_tight_loadfail"
    raw["simulator"]["stochastic_processes"]["node_failure"]["mode"] = "per_node_bernoulli"
    return raw


VARIANTS = {
    "env_tight": _tight,
    "env_loadfail": _loadfail,
    "env_tight_loadfail": _tight_loadfail,
}

HEADER = (
    "# GENERATED by scripts/hardening/make_env_configs.py from config/default.yaml.\n"
    "# Stage-B (Phase-2) environment-variation config. Do not edit by hand;\n"
    "# edit the generator and re-run. Differs from default.yaml only in the\n"
    "# documented overrides for variant: {name}.\n"
)


def main() -> None:
    raw = _load_default_raw()
    out_dir = REPO_ROOT / "config"
    for name, fn in VARIANTS.items():
        variant_raw = fn(raw)
        # Validate before writing — fail loudly on a bad override.
        build_run_config(variant_raw)
        path = out_dir / f"{name}.yaml"
        with path.open("w", encoding="utf-8") as handle:
            handle.write(HEADER.format(name=name))
            yaml.safe_dump(variant_raw, handle, sort_keys=False, default_flow_style=False)
        cfg = build_run_config(variant_raw)
        n_templates = len(cfg.simulator.dag_templates)
        nf = cfg.simulator.stochastic_processes.node_failure.mode
        print(f"wrote {path.name:24} | dag_templates={n_templates} | node_failure={nf}")


if __name__ == "__main__":
    main()
